### ISSUE TITLE
Resampling

### ISSUE THREAD

**Issue by apryor6** [mattmills49/Kaggle_Comps#6]
For products with extremely small numbers of purchasers, the probabilities returned will be quite high even though the product is not very likely to be bought in reality. We will probably need to resample the data to make the probabilities more meaningful, or try strategies where we completely ignore certain products

**Comment by mattmills49** [comment]
> For products with extremely small numbers of purchasers, the probabilities returned will be quite high even though the product is not very likely to be bought in reality

Can you explain a little more? If the products are pretty rare then the model, well I guess any GAM/Logistic Regression model, should be pretty selective about predicting anyone to buy them in the first place. If anything models would just default to predicting everyone not to buy a rare product since there isn't that much data to go off of. Maybe I'm just misunderstanding what you mean lol.

**Comment by apryor6** [comment]
Sorry, that wasn't very clear. By the probabilities returned being "high", I really meant "biased". Some products are owned by like half of people, and others are only owned by a small handful. With no resampling, the model will naturally favor the products that are more commonly owned, but this would fail to capture information about demographics that are smaller but more predictable. In other words, the same problem you always have with heavily imbalanced classes.

---

Alan (AJ) Pryor
Ph.D. Candidate
UCLA Coherent Imaging Group
University of California, Los Angeles
Department of Physics and Astronomy

## (478-232-2486)

**Comment by apryor6** [comment]
I did a couple of tests on against the leaderboard with interesting results. To see the importance of the minority classes, I reran the classification script but only considered the 12 most commonly owned features, and the score _dropped by almost 50%_. Currently, I am just using 1e6 of the rows in the training data, but I also tried increasing that to 2e6, and the score also dropped slightly. These results indicate to me that:
- The minority classes are very important, and I think resampling will be critical. Granted, the most commonly owned products also are the ones most likely to be "unbuyable" and therefore potentially unable contribute to scoring, so it's possible part of the score drop was due to not providing 7 valid recommendations. However, with 12 possible products a customer would have to own more than 5 before you would start degrading in this fashion, and I just checked and only 2.7% of observations possess 5 or more products.
- My current model is overfit. This doesn't surprise me as we still haven't implemented any cross-validation or regularization.

It seems the package `ROSE` has exactly what we need, as described [here](https://www.analyticsvidhya.com/blog/2016/03/practical-guide-deal-imbalanced-classification-problems/). It can do simultaneous over/undersampling so that we can reduce the size of the dataset to something more manageable without throwing out all of the data to match the rare classes.  

I suspect with resampling the data combined with an actual model with cv-tuning and regularization we will see significant improvement

**Comment by mattmills49** [comment]
Ok that makes more sense. I'd be curious to see the trade-offs of oversampling on a good algorithm, since there really isn't a penalty to predicting something they don't buy there might not be much downside. Something we will have to track. By the way, most algorithms in R have a `weight` argument where you can weight certain observations in the function call itself and weighting is mathematically equivalent to under/over sampling. Just may make it easier to keep track of.
